---

- name: "Create a directory {{ docker_compose.path }}"
  file:
    path: "{{ docker_compose.path }}"
    state: "directory"
    owner: root
    group: root
    mode: '0755'

- name: "Copy file {{ docker_compose.path }}/docker-compose.yml"
  synchronize:
    src: "{{ lookup('first_found', file) }}"
    dest: "{{ docker_compose.path }}/docker-compose.yml"
  vars:
    file:
      - "../../extra_perso/{{ ansible_hostname }}/docker/docker_compose/docker-compose.yml"
      - "../../extra/{{ ansible_hostname }}/docker/docker_compose/docker-compose.yml"
      - "files/docker-compose.yml"
  register: compose

- name:  Up container
  shell: "{{ docker_script.path }}/docker_up.sh"
  when: compose.changed

