---

- name: Setting fact for Proxy
  set_fact:
    sys_path: "directory"
  when: (proxy.state == 'present')

- name: Setting fact for no Proxy
  set_fact:
    sys_path: "absent"
  when: (proxy.state == 'absent')

- name: Create a directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: "{{ sys_path }}"
    owner: root
    group: root
    mode: '0755'

- name: Proxy | {{ proxy.state }}
  action: template dest=/etc/systemd/system/docker.service.d/http-proxy.conf src=http-proxy.conf.j2 owner=root group=root
  when: proxy.state == 'present'
  register: proxy

- name: Conf systemd no iptables
  lineinfile:
    path: "/lib/systemd/system/docker.service"
    regexp: '^ExecStart=\/usr\/bin\/dockerd -H fd:\/\/'
    line: 'ExecStart=/usr/bin/dockerd -H fd:// --iptables=false'
  register: iptable

#- name: Conf init no iptables
#  lineinfile:
#    path: "/etc/init.d/docker"
#    regexp: '^DOCKER_OPTS='
#    line: 'DOCKER_OPTS="iptables=false"'

- name: Reload Systemd
  shell: systemctl daemon-reload
  when: iptable.changed or proxy.changed
  notify: Restart service

- name: Copy path /opt/scripts/docker/
  synchronize: src=scripts/docker dest=/opt/scripts recursive=yes delete=yes

